/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package exportacion.components;

/**
 *
 * @author JuanCarlosEspinozaZu
 */
public class AgregarCliente extends javax.swing.JPanel {

    /**
     * Creates new form AgregarExportacion
     */
    public AgregarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddContainner = new javax.swing.JPanel();
        Containner_Add = new exportacion.swin.PanelRedondo();
        jLabel1 = new javax.swing.JLabel();
        NombreClienteTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IdClienteTxt = new javax.swing.JTextField();
        CrearClienteBtn = new javax.swing.JButton();
        panelRedondo1 = new exportacion.swin.PanelRedondo();

        Containner_Add.setBackground(new java.awt.Color(226, 227, 232));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Agregar Cliente");

        NombreClienteTxt.setBackground(new java.awt.Color(255, 255, 255));
        NombreClienteTxt.setForeground(new java.awt.Color(51, 51, 51));
        NombreClienteTxt.setText("Nombre");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre completo");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Numero de Identificacion");

        IdClienteTxt.setBackground(new java.awt.Color(255, 255, 255));
        IdClienteTxt.setForeground(new java.awt.Color(51, 51, 51));
        IdClienteTxt.setText("x-xxxx-xxxx");

        CrearClienteBtn.setBackground(new java.awt.Color(102, 102, 102));
        CrearClienteBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        CrearClienteBtn.setText("Agregar");
        CrearClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearClienteBtnActionPerformed(evt);
            }
        });

        panelRedondo1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelRedondo1Layout = new javax.swing.GroupLayout(panelRedondo1);
        panelRedondo1.setLayout(panelRedondo1Layout);
        panelRedondo1Layout.setHorizontalGroup(
            panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        panelRedondo1Layout.setVerticalGroup(
            panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Containner_AddLayout = new javax.swing.GroupLayout(Containner_Add);
        Containner_Add.setLayout(Containner_AddLayout);
        Containner_AddLayout.setHorizontalGroup(
            Containner_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Containner_AddLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(Containner_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(Containner_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CrearClienteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                        .addComponent(NombreClienteTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRedondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Containner_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Containner_AddLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addGroup(Containner_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(IdClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(681, Short.MAX_VALUE)))
        );
        Containner_AddLayout.setVerticalGroup(
            Containner_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Containner_AddLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CrearClienteBtn)
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(Containner_AddLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelRedondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Containner_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Containner_AddLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(IdClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(346, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout AddContainnerLayout = new javax.swing.GroupLayout(AddContainner);
        AddContainner.setLayout(AddContainnerLayout);
        AddContainnerLayout.setHorizontalGroup(
            AddContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddContainnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Containner_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AddContainnerLayout.setVerticalGroup(
            AddContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddContainnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Containner_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddContainner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddContainner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearClienteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearClienteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddContainner;
    private exportacion.swin.PanelRedondo Containner_Add;
    private javax.swing.JButton CrearClienteBtn;
    private javax.swing.JTextField IdClienteTxt;
    private javax.swing.JTextField NombreClienteTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private exportacion.swin.PanelRedondo panelRedondo1;
    // End of variables declaration//GEN-END:variables
}
